# Generated by Django 5.2.7 on 2025-10-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='color',
            field=models.CharField(default='#eef7e8', max_length=50),
        ),
    ]
