# Generated by Django 5.2.7 on 2025-10-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_coupon_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='color',
        ),
        migrations.AddField(
            model_name='certification',
            name='style_class',
            field=models.CharField(choices=[('pill-green', 'Green'), ('pill-orange', 'Orange'), ('pill-blue', 'Blue')], default='pill-green', max_length=50),
        ),
    ]
