# Generated by Django 5.2.7 on 2025-10-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_product_calories_remove_product_carbs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Đã đặt'), ('processing', 'Đang xử lý'), ('confirmed', 'Đã xác nhận'), ('shipping', 'Đang vận chuyển'), ('completed', 'Hoàn tất'), ('canceled', 'Đã hủy')], default='placed', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'COD'), ('momo', 'Momo'), ('vnpay', 'VNPay'), ('bank', 'Chuyển khoản')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
    ]
