# Generated by Django 5.2.7 on 2025-10-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_coupon_is_public_customer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referee',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='rewardtransaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='points',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='referred_by',
        ),
        migrations.DeleteModel(
            name='CouponAssignment',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='RewardTransaction',
        ),
    ]
