# Generated by Django 5.2.7 on 2025-10-06 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_referral_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='combos/'),
        ),
    ]
