# Generated by Django 5.2.7 on 2025-10-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'AI Assistant',
                'verbose_name_plural': 'AI Assistant',
                'managed': False,
            },
        ),
    ]
